# Feature Engineering

This notebook focuses on preparing the cleaned student performance dataset for machine learning.

The main objectives of this stage are:

- Select relevant features for model development.
- Remove non-predictive identifier columns.
- Analyze and handle potential outliers where necessary.
- Encode categorical variables into numerical form.
- Define the input features and target variable.
- Prepare the final dataset for machine learning.

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split

pd.set_option("display.max_columns", None)

In [8]:
df = df = pd.read_csv("../data/processed/student_performance_cleaned.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

Dataset loaded successfully!
Shape: (2480, 20)

,Student_ID,Student_Name,Age,Gender,Department,Semester,Study_Hours_Per_Day,Attendance_Percentage,Previous_Semester_Marks,Assignment_Average,Internal_Test_Marks,Practical_Marks,Participation_Score,Sleep_Hours,Internet_Access,Study_Resources,Backlogs,Final_Exam_Marks,Pass_Fail,Performance_Category
0,S23AIM001,Tanushree Tiwari,20.0,Female,CSE (AI & ML),5,3.50,89.5,76.5,19.0,25.0,40,9.0,7.0,Yes,Textbooks,0.0,77.0,Pass,Very Good
1,S23AIM002,Nitin Kundu,21.0,Male,CSE (AI & ML),5,1.00,71.5,32.0,8.0,4.0,22,7.0,7.0,Yes,Online Courses,4.0,16.0,Fail,Needs Improvement
2,S23AIM003,Amit Laha,21.0,Male,CSE (AI & ML),5,5.50,78.4,82.0,20.0,26.5,45,5.0,6.0,Yes,Notes Only,2.0,80.0,Pass,Very Good
3,S23AIM004,Akash Thakur,21.0,Male,CSE (AI & ML),6,4.00,78.9,67.7,16.5,21.5,38,6.0,5.0,Yes,Online Courses,0.0,63.0,Pass,Good
4,S23AIM005,Aarav Rao,22.0,Male,CSE (AI & ML),6,2.94,65.4,49.0,10.0,13.0,34,6.0,5.0,Yes,Both,0.0,47.0,Pass,Needs Improvement

In [9]:
print("Dataset Information:")
print("=" * 50)

df.info()

Dataset Information:
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2480 entries, 0 to 2479
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Student_ID               2480 non-null   object
 1   Student_Name             2480 non-null   object
 2   Age                      2480 non-null   float64
 3   Gender                   2480 non-null   object
 4   Department               2480 non-null   object
 5   Semester                 2480 non-null   int64
 6   Study_Hours_Per_Day      2480 non-null   float64
 7   Attendance_Percentage    2480 non-null   float64
 8   Previous_Semester_Marks  2480 non-null   float64
 9   Assignment_Average       2480 non-null   float64
 10  Internal_Test_Marks      2480 non-null   float64
 11  Practical_Marks          2480 non-null   int64
 12  Participation_Score      2480 non-null   float64
 13  Sleep_Hours              2480 non-null   float64
 14  Internet_Access          2480 non-null   object
 15  Study_Resources          2480 non-null   object
 16  Backlogs                 2480 non-null   float64
 17  Final_Exam_Marks         2480 non-null   float64
 18  Pass_Fail                2480 non-null   object
 19  Performance_Category     2480 non-null   object
dtypes: float64(10), int64(2), object(8)
memory usage: 387.6+ KB

In [4]:
print("Missing Values:")
df.isnull().sum()

Missing Values:

Student_ID                 0
Student_Name               0
Age                        0
Gender                     0
Department                 0
Semester                   0
Study_Hours_Per_Day        0
Attendance_Percentage      0
Previous_Semester_Marks    0
Assignment_Average         0
Internal_Test_Marks        0
Practical_Marks            0
Participation_Score        0
Sleep_Hours                0
Internet_Access            0
Study_Resources            0
Backlogs                   0
Final_Exam_Marks           0
Pass_Fail                  0
Performance_Category       0
dtype: int64

In [5]:
df.head()

,Student_ID,Student_Name,Age,Gender,Department,Semester,Study_Hours_Per_Day,Attendance_Percentage,Previous_Semester_Marks,Assignment_Average,Internal_Test_Marks,Practical_Marks,Participation_Score,Sleep_Hours,Internet_Access,Study_Resources,Backlogs,Final_Exam_Marks,Pass_Fail,Performance_Category
0,S23AIM001,Tanushree Tiwari,20.0,Female,CSE (AI & ML),5,3.50,89.5,76.5,19.0,25.0,40,9.0,7.0,Yes,Textbooks,0.0,77.0,Pass,Very Good
1,S23AIM002,Nitin Kundu,21.0,Male,CSE (AI & ML),5,1.00,71.5,32.0,8.0,4.0,22,7.0,7.0,Yes,Online Courses,4.0,16.0,Fail,Needs Improvement
2,S23AIM003,Amit Laha,21.0,Male,CSE (AI & ML),5,5.50,78.4,82.0,20.0,26.5,45,5.0,6.0,Yes,Notes Only,2.0,80.0,Pass,Very Good
3,S23AIM004,Akash Thakur,21.0,Male,CSE (AI & ML),6,4.00,78.9,67.7,16.5,21.5,38,6.0,5.0,Yes,Online Courses,0.0,63.0,Pass,Good
4,S23AIM005,Aarav Rao,22.0,Male,cse aiml,6,2.94,65.4,49.0,10.0,13.0,34,6.0,5.0,Yes,Both,0.0,47.0,Pass,Needs Improvement

In [6]:
df["Department"].value_counts()

Department
Computer Science & Engineering    629
CSE (AI & ML)                     533
Information Technology            405
Electronics & Communication       386
Mechanical Engineering            304
cse                                16
CSE (AIML)                         16
Comp Sci & Engg                    16
Info Tech                          13
E&C                                12
ece                                12
AI & ML                            11
CSE                                11
CSE(AIML)                          11
Computer Science                   10
information technology             10
IT                                 10
CSE-AIML                            9
C.S.E                               9
Mech. Engg                          9
mech                                8
ECE                                 8
Mechanical                          7
I.T.                                7
cse aiml                            6
Electronics & Comm.                 6
ME                                  6
Name: count, dtype: int64

In [10]:
print(df["Department"].value_counts())

Department
Computer Science & Engineering    691
CSE (AI & ML)                     586
Information Technology            445
Electronics & Communication       424
Mechanical Engineering            334
Name: count, dtype: int64

In [11]:
print("Dataset Shape:", df.shape)

Dataset Shape: (2480, 20)

In [12]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Student_ID                 0
Student_Name               0
Age                        0
Gender                     0
Department                 0
Semester                   0
Study_Hours_Per_Day        0
Attendance_Percentage      0
Previous_Semester_Marks    0
Assignment_Average         0
Internal_Test_Marks        0
Practical_Marks            0
Participation_Score        0
Sleep_Hours                0
Internet_Access            0
Study_Resources            0
Backlogs                   0
Final_Exam_Marks           0
Pass_Fail                  0
Performance_Category       0
dtype: int64

## Removing Non-Predictive Identifier Columns

Student_ID and Student_Name are identifiers rather than meaningful predictive features.

- Student_ID uniquely identifies each student.
- Student_Name identifies the student but does not provide useful information for predicting academic performance.

Therefore, these columns will be removed before preparing the dataset for machine learning.

In [13]:
# Remove non-predictive identifier columns
df = df.drop(columns=["Student_ID", "Student_Name"])

print("Columns after removing identifiers:")
print(df.columns.tolist())

print("\nDataset Shape:", df.shape)

Columns after removing identifiers:
['Age', 'Gender', 'Department', 'Semester', 'Study_Hours_Per_Day', 'Attendance_Percentage', 'Previous_Semester_Marks', 'Assignment_Average', 'Internal_Test_Marks', 'Practical_Marks', 'Participation_Score', 'Sleep_Hours', 'Internet_Access', 'Study_Resources', 'Backlogs', 'Final_Exam_Marks', 'Pass_Fail', 'Performance_Category']

Dataset Shape: (2480, 18)

## Identifying Numerical and Categorical Features

Before encoding the dataset, the features are divided into two groups:

- **Numerical features:** Variables containing numerical values that can be used directly by machine learning models.
- **Categorical features:** Variables containing categories or labels that need to be converted into numerical form.

Identifying these groups helps us apply the appropriate preprocessing technique to each feature.

In [14]:
# Identify numerical and categorical features

numerical_features = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_features = df.select_dtypes(include=["object"]).columns.tolist()

print("Numerical Features:")
print(numerical_features)

print("\nCategorical Features:")
print(categorical_features)

Numerical Features:
['Age', 'Semester', 'Study_Hours_Per_Day', 'Attendance_Percentage', 'Previous_Semester_Marks', 'Assignment_Average', 'Internal_Test_Marks', 'Practical_Marks', 'Participation_Score', 'Sleep_Hours', 'Backlogs', 'Final_Exam_Marks']

Categorical Features:
['Gender', 'Department', 'Internet_Access', 'Study_Resources', 'Pass_Fail', 'Performance_Category']

## Defining the Target Variable

For the regression task, `Final_Exam_Marks` is selected as the target variable.

The model will learn from the student's academic and behavioral features and predict the student's final examination marks.

`Final_Exam_Marks` must not be included among the input features because it is the value we want the model to predict.

In [15]:
# Define features and target

X = df.drop(columns=["Final_Exam_Marks"])
y = df["Final_Exam_Marks"]

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

print("\nTarget variable:")
print(y.head())

Feature shape: (2480, 17)
Target shape: (2480,)

Target variable:
0    77.0
1    16.0
2    80.0
3    63.0
4    47.0
Name: Final_Exam_Marks, dtype: float64

## Removing Target-Leakage Features

`Pass_Fail` and `Performance_Category` describe the student's final performance.

Since the objective is to predict `Final_Exam_Marks`, these columns should not be used as input features. Including them could introduce target leakage and make the model appear more accurate than it actually is.

Therefore, both columns are removed from the feature set.

In [16]:
# Remove target-leakage columns

X = X.drop(columns=["Pass_Fail", "Performance_Category"])

print("Features after removing target-leakage columns:")
print(X.columns.tolist())

print("\nFeature shape:", X.shape)

Features after removing target-leakage columns:
['Age', 'Gender', 'Department', 'Semester', 'Study_Hours_Per_Day', 'Attendance_Percentage', 'Previous_Semester_Marks', 'Assignment_Average', 'Internal_Test_Marks', 'Practical_Marks', 'Participation_Score', 'Sleep_Hours', 'Internet_Access', 'Study_Resources', 'Backlogs']

Feature shape: (2480, 15)

## Splitting the Dataset into Training and Testing Sets

The dataset is divided into training and testing sets before applying preprocessing.

- The training set is used to train the machine learning model.
- The testing set is used to evaluate the model on unseen data.
- An 80/20 split is used, as specified in the project requirements.
- `random_state=42` is used to make the split reproducible.

In [17]:
# Split the dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training feature shape:", X_train.shape)
print("Testing feature shape:", X_test.shape)

print("Training target shape:", y_train.shape)
print("Testing target shape:", y_test.shape)

Training feature shape: (1984, 15)
Testing feature shape: (496, 15)
Training target shape: (1984,)
Testing target shape: (496,)

## Identifying Features for Preprocessing

The input features contain both numerical and categorical variables.

Numerical features can be used directly by machine learning models, while categorical features need to be converted into numerical values.

The categorical features are:

- Gender
- Department
- Internet_Access
- Study_Resources

These features will be encoded in the next preprocessing step.

In [18]:
# Define numerical and categorical input features

categorical_features = [
    "Gender",
    "Department",
    "Internet_Access",
    "Study_Resources"
]

numerical_features = [
    "Age",
    "Semester",
    "Study_Hours_Per_Day",
    "Attendance_Percentage",
    "Previous_Semester_Marks",
    "Assignment_Average",
    "Internal_Test_Marks",
    "Practical_Marks",
    "Participation_Score",
    "Sleep_Hours",
    "Backlogs"
]

print("Categorical Features:")
print(categorical_features)

print("\nNumerical Features:")
print(numerical_features)

print("\nNumber of categorical features:", len(categorical_features))
print("Number of numerical features:", len(numerical_features))

Categorical Features:
['Gender', 'Department', 'Internet_Access', 'Study_Resources']

Numerical Features:
['Age', 'Semester', 'Study_Hours_Per_Day', 'Attendance_Percentage', 'Previous_Semester_Marks', 'Assignment_Average', 'Internal_Test_Marks', 'Practical_Marks', 'Participation_Score', 'Sleep_Hours', 'Backlogs']

Number of categorical features: 4
Number of numerical features: 11

## Creating the Preprocessing Pipeline

The dataset contains both numerical and categorical features, so different preprocessing techniques are required.

- Numerical features will be standardized using `StandardScaler`.
- Categorical features will be converted into numerical values using `OneHotEncoder`.
- `ColumnTransformer` will combine both preprocessing steps into a single pipeline.

The preprocessing object will be fitted only on the training data to avoid data leakage.

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Create preprocessing pipeline

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_features),
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), categorical_features)
    ]
)

print("Preprocessing pipeline created successfully!")

Preprocessing pipeline created successfully!

## Applying the Preprocessing Pipeline

The preprocessing pipeline is fitted using only the training data.

After fitting:

- The training data is transformed using the learned preprocessing parameters.
- The testing data is transformed using the same parameters.
- This prevents information from the testing set from influencing the preprocessing process.

In [20]:
# Fit the preprocessor on training data and transform both datasets

X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("Training data after preprocessing:", X_train_processed.shape)
print("Testing data after preprocessing:", X_test_processed.shape)

Training data after preprocessing: (1984, 47)
Testing data after preprocessing: (496, 47)

## Verifying the Processed Features

After preprocessing, all categorical variables have been converted into numerical columns and the numerical features have been standardized.

The processed training and testing datasets should therefore contain only numerical values.

In [21]:
# Verify the processed data

print("Processed training data type:", X_train_processed.dtype)
print("Processed testing data type:", X_test_processed.dtype)

print("\nTraining data contains NaN:", np.isnan(X_train_processed).any())
print("Testing data contains NaN:", np.isnan(X_test_processed).any())

Processed training data type: float64
Processed testing data type: float64

Training data contains NaN: False
Testing data contains NaN: False

## Inspecting the Processed Feature Names

One-hot encoding expands categorical variables into multiple numerical columns.

We will inspect the names of all processed features to understand the final feature representation used by the machine learning model.

In [22]:
# Get the names of the processed features

feature_names = preprocessor.get_feature_names_out()

print("Number of processed features:", len(feature_names))
print("\nProcessed feature names:")
for feature in feature_names:
    print(feature)

Number of processed features: 47

Processed feature names:
num__Age
num__Semester
num__Study_Hours_Per_Day
num__Attendance_Percentage
num__Previous_Semester_Marks
num__Assignment_Average
num__Internal_Test_Marks
num__Practical_Marks
num__Participation_Score
num__Sleep_Hours
num__Backlogs
cat__Gender_F
cat__Gender_FEMALE
cat__Gender_Female
cat__Gender_Female
cat__Gender_M
cat__Gender_MALE
cat__Gender_Male
cat__Gender_Male
cat__Gender_Other
cat__Gender_female
cat__Gender_male
cat__Department_CSE (AI & ML)
cat__Department_Computer Science & Engineering
cat__Department_Electronics & Communication
cat__Department_Information Technology
cat__Department_Mechanical Engineering
cat__Internet_Access_N
cat__Internet_Access_NO
cat__Internet_Access_No
cat__Internet_Access_Y
cat__Internet_Access_YES
cat__Internet_Access_Yes
cat__Internet_Access_no
cat__Internet_Access_yes
cat__Study_Resources_Both
cat__Study_Resources_Both
cat__Study_Resources_Notes
cat__Study_Resources_Notes Only
cat__Study_Resources_Online
cat__Study_Resources_Online Courses
cat__Study_Resources_Text Books
cat__Study_Resources_Textbooks
cat__Study_Resources_both
cat__Study_Resources_notes only
cat__Study_Resources_online courses
cat__Study_Resources_textbooks

In [23]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

In [24]:
print("Processed training shape:", X_train_processed.shape)
print("Processed testing shape:", X_test_processed.shape)

Processed training shape: (1984, 47)
Processed testing shape: (496, 47)

In [25]:
df = pd.read_csv("../data/processed/student_performance_cleaned.csv")

print(df.shape)

print("\nGender:")
print(df["Gender"].value_counts())

print("\nInternet Access:")
print(df["Internet_Access"].value_counts())

print("\nStudy Resources:")
print(df["Study_Resources"].value_counts())

(2480, 20)

Gender:
Gender
Male      1430
Female    1018
Other       32
Name: count, dtype: int64

Internet Access:
Internet_Access
Yes    2270
No      210
Name: count, dtype: int64

Study Resources:
Study_Resources
Both              887
Online Courses    668
Textbooks         537
Notes Only        388
Name: count, dtype: int64

In [27]:
# Remove identifier columns
df = df.drop(columns=["Student_ID", "Student_Name"])

# Define features and target
X = df.drop(columns=["Final_Exam_Marks"])
y = df["Final_Exam_Marks"]

# Remove target leakage columns
X = X.drop(columns=["Pass_Fail", "Performance_Category"])

print("X shape:", X.shape)
print("y shape:", y.shape)
print("\nFeatures:")
print(X.columns.tolist())

X shape: (2480, 15)
y shape: (2480,)

Features:
['Age', 'Gender', 'Department', 'Semester', 'Study_Hours_Per_Day', 'Attendance_Percentage', 'Previous_Semester_Marks', 'Assignment_Average', 'Internal_Test_Marks', 'Practical_Marks', 'Participation_Score', 'Sleep_Hours', 'Internet_Access', 'Study_Resources', 'Backlogs']

In [28]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

X_train: (1984, 15)
X_test: (496, 15)

In [26]:
print("Processed training shape:", X_train_processed.shape)
print("Processed testing shape:", X_test_processed.shape)

Processed training shape: (1984, 47)
Processed testing shape: (496, 47)

In [29]:
categorical_features = [
    "Gender",
    "Department",
    "Internet_Access",
    "Study_Resources"
]

numerical_features = [
    "Age",
    "Semester",
    "Study_Hours_Per_Day",
    "Attendance_Percentage",
    "Previous_Semester_Marks",
    "Assignment_Average",
    "Internal_Test_Marks",
    "Practical_Marks",
    "Participation_Score",
    "Sleep_Hours",
    "Backlogs"
]

print("Categorical features:")
print(categorical_features)

print("\nNumerical features:")
print(numerical_features)

Categorical features:
['Gender', 'Department', 'Internet_Access', 'Study_Resources']

Numerical features:
['Age', 'Semester', 'Study_Hours_Per_Day', 'Attendance_Percentage', 'Previous_Semester_Marks', 'Assignment_Average', 'Internal_Test_Marks', 'Practical_Marks', 'Participation_Score', 'Sleep_Hours', 'Backlogs']

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_features),
        (
            "cat",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            ),
            categorical_features
        )
    ]
)

print("Preprocessor created successfully!")

Preprocessor created successfully!

In [31]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("Processed training shape:", X_train_processed.shape)
print("Processed testing shape:", X_test_processed.shape)

Processed training shape: (1984, 25)
Processed testing shape: (496, 25)

In [32]:
feature_names = preprocessor.get_feature_names_out()

print("Number of features:", len(feature_names))

print("\nFeature names:")
for feature in feature_names:
    print(feature)

Number of features: 25

Feature names:
num__Age
num__Semester
num__Study_Hours_Per_Day
num__Attendance_Percentage
num__Previous_Semester_Marks
num__Assignment_Average
num__Internal_Test_Marks
num__Practical_Marks
num__Participation_Score
num__Sleep_Hours
num__Backlogs
cat__Gender_Female
cat__Gender_Male
cat__Gender_Other
cat__Department_CSE (AI & ML)
cat__Department_Computer Science & Engineering
cat__Department_Electronics & Communication
cat__Department_Information Technology
cat__Department_Mechanical Engineering
cat__Internet_Access_No
cat__Internet_Access_Yes
cat__Study_Resources_Both
cat__Study_Resources_Notes Only
cat__Study_Resources_Online Courses
cat__Study_Resources_Textbooks

In [33]:
print("Training data type:", X_train_processed.dtype)
print("Testing data type:", X_test_processed.dtype)

print("\nMissing values in training data:", np.isnan(X_train_processed).any())
print("Missing values in testing data:", np.isnan(X_test_processed).any())

Training data type: float64
Testing data type: float64

Missing values in training data: False
Missing values in testing data: False

## Final Feature Engineering Summary

The cleaned student performance dataset was prepared for machine learning using the following steps:

- Removed non-predictive identifier columns: `Student_ID` and `Student_Name`.
- Selected `Final_Exam_Marks` as the target variable.
- Removed `Pass_Fail` and `Performance_Category` because they are derived from the final exam result and could cause target leakage.
- Split the dataset into training and testing sets using an 80:20 ratio with `random_state=42`.
- Standardized numerical features using `StandardScaler`.
- Converted categorical features into numerical form using `OneHotEncoder`.
- Used `handle_unknown="ignore"` to safely handle unseen categories in the test data.
- The final preprocessing pipeline produced 25 machine-learning features.
- No missing values are present in the processed training or testing data.

In [34]:
print("Final Feature Engineering Summary")
print("-" * 40)
print("Original dataset shape: (2480, 20)")
print("Features before preprocessing: 15")
print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])
print("Final processed features:", X_train_processed.shape[1])
print("Training processed shape:", X_train_processed.shape)
print("Testing processed shape:", X_test_processed.shape)
print("Missing values in training:", np.isnan(X_train_processed).any())
print("Missing values in testing:", np.isnan(X_test_processed).any())

Final Feature Engineering Summary
----------------------------------------
Original dataset shape: (2480, 20)
Features before preprocessing: 15
Training samples: 1984
Testing samples: 496
Final processed features: 25
Training processed shape: (1984, 25)
Testing processed shape: (496, 25)
Missing values in training: False
Missing values in testing: False